#!/bin/bash

# tmux new -s "proj" -d;

# while ["$#" -gt 0]; do
# 	curr=$1
# 	shift

# 	case $curr in
# 		"-m")
# 			tmux neww -t "proj" -n "vim";;
# 		*)

if [[ $# -eq 1 ]]; then
    selected=$1
else
    items=`find ~/proj -maxdepth 2 -mindepth 1 -type d`
    items+=("$HOME/New-folder")
    selected=`echo "$items" | fzf`
fi

dirname=`basename $selected`

tmux switch-client -t $dirname
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c $selected -d -s $dirname && tmux switch-client -t $dirname || tmux new -c $selected -A -s $dirname
