local k = require("keybindings")

require('go').setup({
	disable_defaults = false,
	go='go',
	goimport='gopls',
	fillstruct = 'gopls',
	gofmt = 'gofumpt',
	max_line_len = 128,
	tag_transform = false,
	gotests_template = "testify",
	gotests_template_dir = "",
	comment_placeholder = '' ,
	icons = {breakpoint = '🧘', currentpos = '🏃'},
	verbose = false,
	lsp_cfg = true,
	lsp_gofumpt = true,
	lsp_on_attach = nil,
	lsp_keymaps = k.lsp_bindings,
	lsp_codelens = true,
	lsp_diag_hdlr = false,
	lsp_diag_virtual_text = { space = 1, prefix = "ﱢ" },
	lsp_diag_signs = true,
	lsp_diag_update_in_insert = false,
	lsp_document_formatting = true,
	lsp_inlay_hints = {
		enable = true,
		only_current_line = false,
		only_current_line_autocmd = "CursorHold",
		show_variable_name = true,
		parameter_hints_prefix = "",
		show_parameter_hints = false,
		other_hints_prefix = "=>",
		max_len_align = false,
		max_len_align_padding = 1,
		right_align = false,
		right_align_padding = 6,
		highlight = "Comment",
	},
	gopls_cmd = nil,
	gopls_remote_auto = false,
	gocoverage_sign = "█",
	sign_priority = 5,
	dap_debug = false,
	dap_debug_keymap = false,
	dap_debug_gui = false,
	dap_debug_vt = false,
	build_tags = "tag1,tag2",
	textobjects = true,
	test_runner = 'go',
	verbose_tests = true,
	run_in_floaterm = true,
	trouble = false,
	test_efm = false,
	luasnip = true,
})
