require('plugins')
require('settings')
require('keybindings').default_bindings()
require('lsp_config').config()
require('lsp_servers')
require('nvim_compe')
require('tree_sitter')
require('lua_line')
require('telescope_config')
require("nvim_tree")
require("harpoon").setup( {global_settings = { save_on_toggle = false, save_on_change = true, }})
require("formatter_nvim")
