#!/bin/bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    items=`find ~/proj ~/cp -maxdepth 2 -mindepth 1 -type d`
    selected=`echo "$items" | fzf`
fi

dirname=`basename $selected`
name=${dirname:0:3}

tmux switch-client -t $name
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c $selected -d -s $name && tmux switch-client -t $name || tmux new -c $selected -A -s $name
